name: customizable_snackbar_example
description: Example app for customizable_snackbar package
publish_to: 'none'

environment:
  sdk: ^3.0.0
  flutter: '>=3.0.0'

dependencies:
  customizable_snackbar:
    path: ../
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

