name: customizable_snackbar
description: A Flutter package providing customizable snackbars with queue management, animations, and dismissible functionality.
version: 1.1.1
homepage: https://github.com/mabiloft/customizable_snackbar
repository: https://github.com/mabiloft/customizable_snackbar
issue_tracker: https://github.com/mabiloft/customizable_snackbar/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

platforms:
  android:
  ios:


dependencies:
  figma_squircle: ^0.6.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_riverpod: '>=2.6.1 <4.0.0'
  freezed_annotation: '>=2.4.4 <4.0.0'
  riverpod_annotation: '>=2.6.1 <4.0.0'
  uuid: '>=4.5.1 <5.0.0'

dev_dependencies:
  build_runner: ^2.4.0
  flutter_lints: '>=5.0.0 <7.0.0'
  flutter_test:
    sdk: flutter
  freezed: '>=2.5.0 <4.0.0'
  riverpod_generator: '>=2.3.0 <4.0.0'
  very_good_analysis: ^10.0.0
