name: customizable_snackbar
description: A Flutter package providing customizable snackbars with queue management, animations, and dismissible functionality.
version: 1.0.0
homepage: https://github.com/mabiloft/customizable_snackbar
repository: https://github.com/mabiloft/customizable_snackbar
issue_tracker: https://github.com/mabiloft/customizable_snackbar/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

platforms:
  android:
  ios:

dependencies:
  figma_squircle: ^0.6.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0
  riverpod_annotation: ^3.0.3
  uuid: ^4.5.2

dev_dependencies:
  build_runner: ^2.4.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  riverpod_generator: ^3.0.3
  very_good_analysis: ^10.0.0

